id: P8E4D05A5
initial_creation_type: input
source_metadata:
  title: Topical Outlines
  language: bo
  description: 'A series of topical or thematic outlines (sa bcad):'
  volume:
    f4350908c37945aa97ee96a1deeb72fb:
      title: Synopsis of the Treasury of Abhidharma (Abhidharmakośa)
      parent: Abhidharma
    9002ee9b687640a582230c65bd988720:
      title: 'The Precious Jewelled Key: A Synopsis of the Aspiration of the Great
        Perfection Mañjuśrī'
      parent: Aspiration Prayers
    2950fd940f444493a919bb7041a72341:
      title: The Way to Explain the King of All Aspiration Prayers, the Secret Vajra
        Knot
      parent: Aspiration Prayers
    0491358b77934cc1a2a58fb9628577c3:
      title: A Topical Outline of the General Confession Spoken by the Five Great
        Sages
      parent: Confession
    6f52c07d8329479295a5ea3970fd3322:
      title: Topical Outline of the Prayer That Swiftly Fulfils All Wishes (Sampa
        Nyur Drupma)
      parent: Guru Rinpoche Prayers
    b30fd13c934c4e85ba7029ba4fe83b8d:
      title: Concise Explanatory Outline of the Heart of Wisdom
      parent: Prajñāpāramitā
    27f4db3d46c84cf29ce137660a32a959:
      title: Outline of the Ten Royal Sūtras
      parent: Sūtras
    cc0bc47f9f854fcaa71202b5ddd8013c:
      title: An Outline of The Praise to Tārā with Twenty-One Verses of Homage
      parent: Tārā
created_at: '2022-03-01T06:23:56.644735'
last_modified_at: '2022-03-01T06:23:56.644738'
statistics:
  total_words: 4708
  total_non_words: 490
quality:
  non_words_ratio: 0.1
